### ISSUE TITLE
Table of appropriate analyses

### ISSUE THREAD

**Issue by ismayc** [rudeboybert/fivethirtyeight#22]
Maybe a good task for a student? Create a table of all of the datasets and the types of problems each dataset would be good for:

- Descriptive (plots, summary stats)
- Inference (specify types of variables included and how many)
- Modeling (regression, multiple regression, etc.)

**Comment by rudeboybert** [comment]
Or maybe crowd-sourced via a Google docs with a `.Rmd` file submission field?

**Comment by ismayc** [comment]
Ah, like a Google Form that feeds a Google Sheet that we could read in and display as a `DT::datatable()`?

**Comment by rudeboybert** [comment]
Maybe not linked automagically so we can vouch for the inputs first.

**Comment by ismayc** [comment]
Makes sense.
