### ISSUE TITLE
Failure to find functions in Bechdel analysis vignette

### ISSUE THREAD

**Issue by aegerton** [rudeboybert/fivethirtyeight#24]
When running the final two ggplot codes within the vignette, error messages are returned as follows;-

Error in scale_fill_fivethirtyeight() : 
  could not find function "scale_fill_fivethirtyeight"

Error in theme_fivethirtyeight() : 
  could not find function "theme_fivethirtyeight"

**Comment by ismayc** [comment]
Hi @aegerton. Make sure to install the `ggthemes` package via `install.packages("ggthemes")`.

**Comment by aegerton** [comment]
That fixed it.  Thanks!
