### ISSUE TITLE
Tidy Data Principles for Intro Stats & Data Science Courses: The `fivethirtyeight` R Package

### ISSUE THREAD

**Issue by rudeboybert** [rudeboybert/fivethirtyeight#5]
Hi @hadley! First off, thanks for looking at our package and making pull requests #1  and #2. We're honoured that you're watching!

@chesterismay, @jchunn, and I are working on a [Technology Innovations in Statistics Education (TISE)](http://escholarship.org/uc/uclastat_cts_tise) paper describing the `fivethirtyeight` package: *Tidy Data Principles for Intro Stats & Data Science Courses: The `fivethirtyeight` R Package*.

The outline is in [`fivethirtyeight/TISE`](https://github.com/rudeboybert/fivethirtyeight/tree/master/TISE). We would love your input, in particular with regards to our Proposal, outlined in the ["The Proposal"](https://github.com/rudeboybert/fivethirtyeight/tree/master/TISE#the-proposal) section.

Any advice/input you could offer would be much appreciated.

**Comment by hadley** [comment]
Could you please send me an email with a deadline? That's more likely to get a useful response :)
