### ISSUE TITLE
Variable documentation

### ISSUE THREAD

**Issue by abarylsky** [rudeboybert/fivethirtyeight#57]
I'm working on the democratic primary candidates 2018 csv and I have several questions. 
1. The README file says the variable gender exists in the dem-candidates dataset but it doesn't. Should I remove this from the README file?
2. The README file has descriptions for each variable already. Should I copy these descriptions for the description file I'm creating for each variable?
3. I'm not sure what to put for the source in the description file. A lot of the variables have different sources. For instance, some say "Supplied by Ballotpedia," some say they're from the candidate's website, some from NYTimes, etc.

**Comment by rudeboybert** [comment]
Hey @abarylsky, looking at the `data-raw/primary-candidates-2018` folder:

1. Leave the `README` as is given that it's written by 538 and not by us. In fact, it seems somebody has filed this as an issue on their GitHub: https://github.com/fivethirtyeight/data/issues/211
2. Do you mean "copy these descriptions for the _R help/documentation file that will pop up when I run `?DATASET_NAME`" If so, then yes.
3. That will get annoying. Simply cite all sources once in the `@source` section of the `roxygen2` code you'll be writing in `R/data_alina.R`. I think that will suffice

**Comment by abarylsky** [comment]
For #3, can I just write the names of the sources and not supply a link if I don't have one provided in the README file?

**Comment by rudeboybert** [comment]
yep, sounds good

**Comment by rudeboybert** [comment]
Done in #66
