### ISSUE TITLE
data format of riddler castles

### ISSUE THREAD

**Issue by ireneryan** [rudeboybert/fivethirtyeight#71]
Hi Albert, I went through the tidying process for the riddler castles datasets but then realized they might already be tidy? This is what I transformed it into in order to reduce having all the castle_n variables, but it makes the strategy column really redundant. Thoughts? Thanks! 
<img width="580" alt="Screen Shot 2019-11-18 at 7 47 43 PM" src="https://user-images.githubusercontent.com/37080311/69106447-5a72a600-0a3c-11ea-9986-aae96c241ca6.png">

**Comment by rudeboybert** [comment]
Could you create a PR with these edits in `data-raw/process_data_sets_irene.R` so that I can create this data frame for myself?

**Comment by ireneryan** [comment]
That's what I'm in the process of doing, I just wasn't sure if the data should be restructured before submitting the request. I can go ahead and request with what I've done if that's what you mean

**Comment by rudeboybert** [comment]
Yes, please submit the PR and I'll take a closer look. I'm just having a hard time figuring out in the abstract what needs to be done.

**Comment by ireneryan** [comment]
Thank you! Have a good night

**Comment by rudeboybert** [comment]
Done in #72
