### ISSUE TITLE
Add SDS390 datasets to master Google Sheet

### ISSUE THREAD

**Issue by rudeboybert** [rudeboybert/fivethirtyeight#79]
Add following datasets to [Master Google Sheet](https://docs.google.com/spreadsheets/d/1IMWAHNPIDzplafWW6AGnGyHmB1BMjohEw_V5HmT70Gs/edit#gid=840984416). The contents of this Google Sheet ultimately get fed into this webpage listing all [datasets](https://fivethirtyeight-r.netlify.app/articles/fivethirtyeight.html) via `pkgdown`'s compilation of `vignettes/fivethirtyeight.Rmd`.

- [x] By Natalia Iannucci: `media_mentions_cable`, `media_mentions_online`
- [x] By Marium Tapal: `state_index`, `state_words`
- [x] By Lizette Carpenter: `cabinet_turnover`
- [x] By Irene Ryan: `castle_solutions`, `castle_solutions_2`, `castle_solutions_3`
- [x] By Alina Barylsky: `dem_candidates`
- [x] By Rana Gahwagy:`quasi_winshares`
- [x] By Danica Miguel : `raptor_by_player`,`raptor_by_team`
- [x] By Sunni Raleigh: `wwc_2019_forecasts`, `wwc_2019_matches`
- [x] By Anna Ballou: `foul_balls` 
- [x] By Jane Bang: `nba_draymond`
- [x] By Jordan Moody: `fight_songs`
- [x] By Kara Van Allen: `nba_elo`, `nba_elo_latest`
- [x] By Jessica Keast: `nba_all_elo`
- [x] By Fatima Keita: `impeachment_polls`

**Comment by mariumtapal** [comment]
@rudeboybert All done, except for Alina's dataset! There are two articles linked to this dataset with relevant entries in the google sheet highlighted in red.
