### ISSUE TITLE
Update to `comic_characters` vignette

### ISSUE THREAD

**Issue by mariumtapal** [rudeboybert/fivethirtyeight#86]
Hi @jonathanbouchet 

In the next release of the `fivethirtyeight` package, we are transitioning large datasets, including `comic_characters` (used in your user-submitted [vignette](https://fivethirtyeight-r.netlify.app/articles/comics_gender.html)) to the [`fivethirtyeightdata`](https://github.com/fivethirtyeightdata/fivethirtyeightdata) package, where they will be available in full instead of a preview. 

Since the dataset is read-in and cleaned manually (with the code provided in the help file), the vignette doesn't need to be changed, but we would like to include a message indicating the updated location of the dataset.

Please let us know if this is okay!

**Comment by jonathanbouchet** [comment]
sure, please make the change.
